name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  ci:
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        platform: [ubuntu-18.04]
        otp: [21.x, 22.x, 23.x]
        elixir: [1.9.x, 1.10.x, 1.11.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache Mix
        uses: actions/cache@v1
        with:
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-mix-${{hashFiles(format('{0}{1}', github.workspace, '/mix.lock'))}}
          path: _build

      - name: Install dependencies
        run: mix deps.get

      # - name: Compile with warnings
      #   run: mix compile --warnings-as-errors

      - name: Run formatter
        run: mix format --check-formatted

      # - name: Run Credo
      #   run: mix credo

      - name: Run tests
        run: mix test

      - name: Run dialyzer
        run: mix dialyzer