name: Publish to Hex

on:
  release:
    types:
      - created
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.10.4
          otp-version: 22.2

      - name: Get dependencies
        run: mix deps.get

      - name: Publish to hex
        run: mix hex.publish --yes --organization supabase
